---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-nfs
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
