---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    # we can only have one pod attached to the disk at a time,
    # so just kill the pod and roll out the new one right after. This process
    # will cause downtime, and is the sole reason we run this deployment on
    # non preemptable instances
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nfs-server
      role: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
        role: nfs-server
    spec:
      # GKE worker node's with the label 'purpose=nfs' are not preemptable, therefore
      # they are perfectly suitable for running an NFS server. If you need a more reliable
      # solution, see the Notes section in the readme of this repo
      nodeSelector:
        purpose: nfs
      containers:
      - name: nfs-server
        # google propvides a nice NFS server image
        image: gcr.io/google_containers/volume-nfs:0.8
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        # take advantage of gauranteed QoS, we want the NFS pod to be evicted
        # last in a situation where contention is high. All WordPress pods
        # rely on NFS being available
        # https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/
        #
        # 500m / 500Mi CPU / MEM is overkill for hosting 10 sites with low traffic
        # but gaurantees that the worker node keeps enough resources in reserve
        # so the NFS server can provide consistent performance
        resources:
          requests:
            cpu: 500m
            memory: "500Mi"
          limits:
            cpu: 500m
            memory: "500Mi"
        volumeMounts:
          - mountPath: /exports
            name: wordpress
      volumes:
        - name: wordpress
          gcePersistentDisk:
            pdName: wordpress
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server
    role: nfs-server
